version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn install
artifacts:
  files:
    - target/java-artifacts.zip
reports:
   new-report-group:
      files:
        - "**/*"
      base-directory: 'target/surefire-reports'
      discard-paths: no       
